version: '2'
services:
  nicotine:
    image: mcmaldonado/nicotine
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    volumes:
      - /tmp/media:/home/nicotine/media
      - /tmp/config:/home/nicotine/.config
    ports:
      - 5900:5900
    networks:
      - x11
  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
