#!/usr/bin/with-contenv bash
if [ -n "$PASSWORD" ]; then
    echo "abc:${PASSWORD}" | chpasswd
    echo "**** Setting password from environment variable. ****"
else
    echo "**** No auth enabled. To enable auth, you can set the PASSWORD var in docker arguments. ****"
fi

chown -R abc:abc \
    /config \
    /media \
    /squashfs-root